# Site settings
title: Mo Lawson
email: mo@molawson.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: 'http://blog.molawson.com' # the base hostname & protocol for your site
twitter_username: molawson
github_username:  molawson

# Build settings
markdown: kramdown
